-- This is working ok right now.
-- print("Hari0")
UI = require "ui/ui"
-- print("Hari1")
local dashboard_transform = lovr.math.newMat4( vec3( 0, 1.5, -1 ) )
-- print("Hari2")

function lovr.load()
    -- print("Hari3")
    UI.Init(nil, nil, true, 0)
    -- print("Hari4")
    lovr.graphics.setBackgroundColor( 0.4, 0.4, 1 )
    -- print("Hari5")
end
function lovr.update( dt )
    -- print("Hari6")
    UI.InputInfo()
    -- print("Hari7")
end
function lovr.draw( pass )
    -- print("Hari8")
    pass:setColor( .1, .1, .12 )
    -- print("Hari9")
    pass:plane( 0, 0, 0, 25, 25, -math.pi / 2, 1, 0, 0 )
    -- print("Hari10")
    pass:setColor( .2, .2, .2 )
    -- print("Hari11")
    pass:plane( 0, 0, 0, 25, 25, -math.pi / 2, 1, 0, 0, 'line', 50, 50 )
    -- print("Hari12")
    UI.NewFrame( pass )
    -- print("Hari13")
    UI.Begin( "dashboard", dashboard_transform )
    -- print("Hari14")
    UI.ImageButton( "ui/lovrlogo.png", 64, 64 )
    -- print("Hari15")
    UI.SameLine()
    -- print("Hari16")
    UI.Label( os.date() )
    -- print("Hari17")
    UI.SameLine()
    -- print("Hari18")
    -- UI.ImageButton( "battery.png", 64, 64 )
    UI.SameLine()
    -- print("Hari19")
    UI.Dummy( 500, 0 )
    -- print("Hari20")
    UI.SameLine()
    -- print("Hari21")
    UI.ImageButton( "ui/lovrlogo.png", 64, 64 )
    -- print("Hari22")
    UI.SameLine()
    -- print("Hari23")
    UI.ImageButton( "triple_dot.png", 64, 64 )
    -- print("Hari24")
    UI.End( pass )
    -- print("Hari25")

    local ui_passes = UI.RenderFrame( pass )
    -- print("Hari26")
    table.insert( ui_passes, pass )
    -- print("Hari27")
    return lovr.graphics.submit( ui_passes )
end
